class CfgPatches
{
	class A3_Data_F_Mark_Loadorder
	{
		addonRootClass="A3_Data_F_Mark";
		requiredAddons[]=
		{
			"A3_Anims_F_Mark",
			"A3_Anims_F_Mark_Deployment",
			"A3_Characters_F_Mark",
			"A3_Data_F_Mark",
			"A3_Dubbing_F_Mark",
			"A3_Dubbing_F_MP_Mark",
			"A3_Functions_F_Mark",
			"A3_Functions_F_MP_Mark",
			"A3_Language_F_Mark",
			"A3_Language_F_MP_Mark",
			"A3_LanguageMissions_F_Mark",
			"A3_LanguageMissions_F_MP_Mark",
			"A3_Missions_F_Mark",
			"A3_Missions_F_Mark_Data",
			"A3_Missions_F_Mark_Video",
			"A3_Missions_F_MP_Mark",
			"A3_Missions_F_MP_Mark_Data",
			"A3_Modules_F_Mark",
			"A3_Modules_F_Mark_FiringDrills",
			"A3_Modules_F_MP_Mark",
			"A3_Modules_F_MP_Mark_Objectives",
			"A3_Music_F_Mark",
			"A3_Music_F_Mark_Music",
			"A3_Sounds_F_Mark",
			"A3_Static_F_Mark",
			"A3_Static_F_Mark_Designator_01",
			"A3_Static_F_Mark_Designator_02",
			"A3_Structures_F_Mark",
			"A3_Structures_F_Mark_Items_Military",
			"A3_Structures_F_Mark_Items_Sport",
			"A3_Structures_F_Mark_Mil_Flags",
			"A3_Structures_F_Mark_Training",
			"A3_Structures_F_Mark_VR_Helpers",
			"A3_Structures_F_Mark_VR_Shapes",
			"A3_Structures_F_Mark_VR_Targets",
			"A3_Supplies_F_Mark",
			"A3_Ui_F_Mark",
			"A3_Ui_F_MP_Mark",
			"A3_Weapons_F_Mark",
			"A3_Weapons_F_Mark_Acc",
			"A3_Weapons_F_Mark_LongRangeRifles_DMR_01",
			"A3_Weapons_F_Mark_LongRangeRifles_DMR_02",
			"A3_Weapons_F_Mark_LongRangeRifles_DMR_03",
			"A3_Weapons_F_Mark_LongRangeRifles_DMR_04",
			"A3_Weapons_F_Mark_LongRangeRifles_DMR_05",
			"A3_Weapons_F_Mark_LongRangeRifles_DMR_06",
			"A3_Weapons_F_Mark_LongRangeRifles_EBR",
			"A3_Weapons_F_Mark_LongRangeRifles_GM6",
			"A3_Weapons_F_Mark_LongRangeRifles_GM6_Camo",
			"A3_Weapons_F_Mark_LongRangeRifles_M320",
			"A3_Weapons_F_Mark_LongRangeRifles_M320_Camo",
			"A3_Weapons_F_Mark_Machineguns_M200",
			"A3_Weapons_F_Mark_Machineguns_MMG_01",
			"A3_Weapons_F_Mark_Machineguns_MMG_02",
			"A3_Weapons_F_Mark_Machineguns_Zafir",
			"A3_Weapons_F_Mark_Rifles_Khaybar",
			"A3_Weapons_F_Mark_Rifles_MK20",
			"A3_Weapons_F_Mark_Rifles_MX",
			"A3_Weapons_F_Mark_Rifles_SDAR",
			"A3_Weapons_F_Mark_Rifles_TRG20"
		};
		requiredVersion=0.1;
		units[]={};
		weapons[]={};
	};
};
