class CfgPatches
{
	class rhs_main_loadorder
	{
		units[]={};
		weapons[]={};
		requiredVersion=1.78;
		requiredAddons[]=
		{
			"rhs_main",
			"rhs_air",
			"rhs_aps",
			"rhs_decals",
			"rhs_sounds",
			"rhs_c_weaponsounds",
			"rhs_weapon_sounds",
			"rhs_c_vehiclesounds",
			"rhs_c_troops",
			"rhs_c_cars",
			"rhs_c_a2port_car",
			"rhs_c_kamaz",
			"rhs_c_zil131",
			"rhs_c_heavyweapons",
			"rhs_c_identity",
			"rhs_c_radars",
			"rhs_c_weapons",
			"rhs_c_airweapons",
			"rhs_c_a2port_air",
			"rhs_c_air",
			"rhs_c_mi28",
			"rhs_c_mig29",
			"rhs_c_radio",
			"rhs_c_trucks",
			"rhs_c_2s1",
			"rhs_c_2s3",
			"rhs_c_a3retex",
			"rhs_c_bmd",
			"rhs_c_bmd_camo",
			"rhs_c_bmp3",
			"rhs_c_bmp",
			"rhs_c_btr",
			"rhs_c_pts",
			"rhs_c_rva",
			"rhs_c_sprut",
			"rhs_c_t72",
			"rhs_c_tanks",
			"rhs_c_a2port_armor",
			"rhs_c_btr70_camo"
		};
		author="$STR_RHS_AUTHOR_FULL";
		url="http://www.rhsmods.org/";
		authorUrl="http://www.rhsmods.org/";
	};
};
