rhs_mag_9k38_rocket
-----
-----
-----
count=1;
deleteParentWhenTriggered=0;
-----
hit=40;
-----
-----
initSpeed=18;
maneuvrability=34;
-----
mass=100;
-----
-----
missileKeepLockedCone=70;
missileLockCone=12;
missileLockMaxDistance=4800;
missileLockMaxSpeed=333;
missileLockMinDistance=300;
-----
submunitionAmmo="rhs_ammo_he_fragments";
submunitionConeAngle=65;
submunitionInitSpeed=1500;
submunitionParentSpeedCoef=0;
thrust=220;
-----
-----
trackLead=0.56;
-----
triggerOnImpact=1;
-----
-----
