class CfgPatches
{
	class rhsusf_main_loadorder
	{
		units[]={};
		weapons[]={};
		requiredVersion=1.78;
		requiredAddons[]=
		{
			"rhsusf_main",
			"rhsusf_optics",
			"rhsusf_uav",
			"rhsusf_decals",
			"rhsusf_sounds",
			"rhsusf_weapon_sounds",
			"rhsusf_c_weaponsounds",
			"rhsusf_c_identity",
			"rhsusf_caiman",
			"rhsusf_c_uav",
			"rhsusf_c_a2port_car",
			"rhsusf_c_heavyweapons",
			"rhsusf_c_airweapons",
			"rhsusf_c_f22",
			"rhsusf_c_hemtt_a2",
			"rhsusf_c_weapons",
			"rhsusf_c_radio",
			"rhsusf_c_troops",
			"rhsusf_c_Caiman",
			"rhsusf_c_ch53",
			"rhsusf_c_fmtv",
			"rhsusf_c_HEMTT_A4",
			"rhsusf_c_hmmwv",
			"rhsusf_c_m109",
			"rhsusf_c_m1117",
			"rhsusf_c_m113",
			"rhsusf_c_m1a1",
			"rhsusf_c_m1a2",
			"rhsusf_c_markvsoc",
			"rhsusf_c_mrzr",
			"rhsusf_c_mtvr",
			"rhsusf_c_rg33",
			"rhsusf_c_RG33L",
			"rhsusf_c_statics",
			"rhsusf_cars",
			"rhsusf_ch53",
			"rhsusf_c_m252",
			"rhsusf_c_melb",
			"rhsusf_c_himars",
			"rhsusf_c_Cougar",
			"rhsusf_c_stryker"
		};
		author="$STR_RHSUSF_AUTHOR_FULL";
		url="http://www.rhsmods.org/";
		authorUrl="http://www.rhsmods.org/";
	};
};
