class CfgPatches
{
		weapons[]={};
		version=1;
	};
};
class CfgWorlds
{
	class GenericNames
	{
		class FEM_Names
		{
			class FirstNames
			{
				emma="Emma";
				katherine="Katherine";
				anna="Anna";
				stephanie="Stephanie";
				alex="Alex";
				olivia="Olivia";
				susan="Susan";
				astra="Astra";
				leah="Leah";
				ruby="Ruby";
				abi="Abi";
				sarah="Sarah";
				lexi="Lexi";
				hannah="Hannah";
				amber="Amber";
				zara="Zara";
				zoe="Zoe";
				jodit="Jodit";
				benardette="Bernardette";
				heidi="Heidi";
				maya="Maya";
				erica="Erica";
				lucy="Lucy";
				alaina="Alaina";
				sade="Sade";
				dahlia="Dahlia";
				alicia="Alicia";
				leanne="Leanne";
				isabel="Isabel";
				martina="Martina";
			};
			class LastNames
			{
				taylor="Taylor";
				walker="Walker";
				quereshi="Quereshi";
				cheung="Cheung";
				lorenz="Lorenz";
				diaz="Diaz";
				Lovatt="Lovatt";
				grey="Grey";
				cohen="Cohen";
				galinsky="Galinsky";
				hale="Hale";
				jackson="Jackson";
				shepard="Shepard";
				watts="Watts";
				osei="Osei";
				bateman="Bateman";
				daniels="Daniels";
				kerry="Kerry";
				cortez="Cortez";
				sparrow="Sparrow";
				smith="Smith";
				arnott="Arnott";
				oakes="Oakes";
				mason="Mason";
				cole="Cole";
				carter="Carter";
				burke="Burke";
				reed="Reed";
				sullivan="Sullivan";
			};
		};
	};
};
